### ISSUE TITLE
JavaScript

### ISSUE THREAD

**Issue by LewisHammy** [LewisHammy/prework-study-guide#5]
# JavaScript

## User Story

As a boot camp student
I want the prework notes to be structured on a webpage
So that I can easily find and read the information

# Acceptance Criteria 

GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I can see the four topics I learned listed along with a suggestion on what I should study first

**Comment by dkumar600** [comment]
will you tell me what is the issue you are having? and what kind of pre work study guide website you want?
Do you have any samples?
